title: "Teaching Experiential Action-based Materials (TEAM)"
description: "http://team-repo.github.io"
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

materials_repo: "https://github.com/TEAM-repo/TEAM-repo-materials/blob/master/"
